# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM python:3.11-slim

# Use unbuffered threadsafe output
env PYTHONUNBUFFERED=1

# Set work directory
WORKDIR /app

# Install dependencies
COPY pyproject.toml uv.lock ./
RUN pip install --upgrade pip \
    && pip install .

# Copy application code
COPY server ./server

# Default command
CMD ["python", "server/main.py"]
